# Generated by Django 5.1.6 on 2025-02-23 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productingredient',
            name='is_removable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='OrderItemCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Добавить'), ('remove', 'Убрать')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredient')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='main.orderitem')),
            ],
        ),
    ]
