# Generated by Django 5.1.6 on 2025-03-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_email_order_full_name_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
