# Generated by Django 5.1.6 on 2025-03-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_courier_user_is_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
